# This file is auto-generated by GoReleaser on release.
# To use: create a repo github.com/itzzritik/homebrew-tap
# and GoReleaser will push this formula there automatically.
#
# Users install with:
#   brew tap itzzritik/tap
#   brew install forged
#
# Once in homebrew-core (30+ stars):
#   brew install forged

class Forged < Formula
  desc "SSH key management - forge your keys, take them anywhere"
  homepage "https://forged.ritik.me"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/itzzritik/forged/releases/download/v#{version}/forged-darwin-arm64.tar.gz"
    else
      url "https://github.com/itzzritik/forged/releases/download/v#{version}/forged-darwin-amd64.tar.gz"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/itzzritik/forged/releases/download/v#{version}/forged-linux-arm64.tar.gz"
    else
      url "https://github.com/itzzritik/forged/releases/download/v#{version}/forged-linux-amd64.tar.gz"
    end
  end

  def install
    bin.install "forged"
    bin.install "forged-sign"
  end
end
